"""
send_rejections.py
-------------------
Reads scored_candidates.csv, finds everyone with status == "rejected", and
emails them their final_candidate_feedback message (generated by the
CrewAI Feedback + Bias-Check agents).

SAFETY: this is the only script in the project that actually sends real
email. It defaults to DRY RUN — it will only print what it would send.
You must pass --send to actually deliver anything, and it will ask for
one confirmation before doing so (unless you pass --yes too).

Usage:
    python send_rejections.py                  # dry run — prints previews, sends nothing
    python send_rejections.py --send            # actually sends, asks to confirm first
    python send_rejections.py --send --yes      # actually sends, no confirmation prompt
    python send_rejections.py --send --limit 3  # cap how many are sent this run

Requires a .env file (see .env.example) with SMTP_USERNAME / SMTP_PASSWORD.
"""

import os
import sys
import time
import smtplib
import argparse
from email.mime.text import MIMEText
from datetime import datetime, timezone

import pandas as pd
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
SCORED_CSV = os.path.join(DATA_DIR, "scored_candidates.csv")
ENRICHED_CSV = os.path.join(DATA_DIR, "enriched_candidates.csv")  # fallback source for email addresses

SLEEP_BETWEEN_EMAILS = 1.0  # seconds, be polite to the SMTP server
SAVE_EVERY = 10             # write progress to scored_candidates.csv every N emails

SUBJECT_TEMPLATE = "Update on your application — {job_role}"
CLOSING_LINE = (
    "\n\nWe appreciate the time you took to apply and encourage you to apply again "
    "for future roles that match your experience.\n\nBest regards,\nRecruiting Team"
)


def load_smtp_config():
    """Reads SMTP settings from environment variables (loaded from .env)."""
    host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    port = int(os.getenv("SMTP_PORT", "587"))
    username = os.getenv("SMTP_USERNAME")
    password = os.getenv("SMTP_PASSWORD")
    from_email = os.getenv("FROM_EMAIL", username)
    from_name = os.getenv("FROM_NAME", "Recruiting Team")
    # If set, every email is redirected here instead of the real candidate
    # address — use this to safely test actual delivery against an inbox
    # you control before ever removing it.
    test_override_email = os.getenv("TEST_OVERRIDE_EMAIL")

    if not username or not password:
        raise RuntimeError(
            "SMTP_USERNAME / SMTP_PASSWORD are not set.\n"
            "Create a .env file next to this script (copy .env.example) and fill them in.\n"
            "For Gmail: use an App Password, not your normal password — "
            "https://myaccount.google.com/apppasswords"
        )

    return {
        "host": host,
        "port": port,
        "username": username,
        "password": password,
        "from_email": from_email,
        "from_name": from_name,
        "test_override_email": test_override_email,
    }


def load_candidates():
    if not os.path.exists(SCORED_CSV):
        sys.exit(
            f"Could not find {SCORED_CSV}.\n"
            "Run the CrewAI agent layer (run_agents.py) first to generate scored_candidates.csv."
        )
    df = pd.read_csv(SCORED_CSV)

    # older scored_candidates.csv files (generated before the email column was
    # added upstream) won't have an 'email' column — backfill it from
    # enriched_candidates.csv rather than failing outright
    if "email" not in df.columns or df["email"].isna().all():
        if not os.path.exists(ENRICHED_CSV):
            sys.exit(
                "scored_candidates.csv has no email addresses and enriched_candidates.csv "
                "isn't available to backfill them. Re-run run_agents.py (it now includes "
                "email in the output) or make sure enriched_candidates.csv is in data/."
            )
        print("No 'email' column found in scored_candidates.csv — backfilling from enriched_candidates.csv")
        enriched = pd.read_csv(ENRICHED_CSV)[["candidate_name", "email"]]
        df = df.drop(columns=["email"], errors="ignore").merge(enriched, on="candidate_name", how="left")

    for col in ["email_sent", "email_sent_at", "email_error"]:
        if col not in df.columns:
            df[col] = pd.Series([None] * len(df), dtype="object")
        else:
            df[col] = df[col].astype("object")

    return df


def build_message(row, smtp_config):
    to_address = smtp_config["test_override_email"] or row["email"]
    subject = SUBJECT_TEMPLATE.format(job_role=row["job_role"])
    body = str(row["final_candidate_feedback"]).strip() + CLOSING_LINE

    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = f"{smtp_config['from_name']} <{smtp_config['from_email']}>"
    msg["To"] = to_address
    return msg, to_address, subject, body


def get_pending_rejections(df, limit=None):
    pending = df[
        (df["status"] == "rejected")
        & df["final_candidate_feedback"].notna()
        & (df["final_candidate_feedback"].astype(str).str.strip() != "")
        & df["email"].notna()
        & (df["email_sent"] != True)  # noqa: E712 - explicit bool compare reads clearer here
    ].copy()
    if limit is not None:
        pending = pending.head(limit)
    return pending


def save_progress(df):
    df.to_csv(SCORED_CSV, index=False)


def dry_run(df, pending, smtp_config):
    print(f"\n=== DRY RUN — {len(pending)} email(s) would be sent. No emails were sent. ===\n")
    for _, row in pending.iterrows():
        msg, to_address, subject, body = build_message(row, smtp_config)
        print(f"To: {to_address}")
        print(f"Subject: {subject}")
        print(f"Body:\n{body}\n")
        print("-" * 60)
    print("\nRun with --send to actually deliver these (and --yes to skip the confirmation prompt).")
    if smtp_config["test_override_email"]:
        print(f"NOTE: TEST_OVERRIDE_EMAIL is set — real sends would all go to {smtp_config['test_override_email']}.")


def send_all(df, pending, smtp_config, skip_confirm=False):
    if smtp_config["test_override_email"]:
        print(f"NOTE: TEST_OVERRIDE_EMAIL is set — every email below will actually go to "
              f"{smtp_config['test_override_email']} instead of the candidate's real address.")

    print(f"\nAbout to send {len(pending)} rejection email(s) via {smtp_config['host']}.")
    if not skip_confirm:
        answer = input("Type 'yes' to proceed, anything else to cancel: ").strip().lower()
        if answer != "yes":
            print("Cancelled. No emails were sent.")
            return

    server = smtplib.SMTP(smtp_config["host"], smtp_config["port"])
    server.starttls()
    server.login(smtp_config["username"], smtp_config["password"])

    sent_count, error_count = 0, 0
    try:
        for i, (idx, row) in enumerate(pending.iterrows(), start=1):
            msg, to_address, subject, _ = build_message(row, smtp_config)
            print(f"[{i}/{len(pending)}] Sending to {to_address} ({row['candidate_name']})...", end=" ")
            try:
                server.send_message(msg)
                df.loc[idx, "email_sent"] = True
                df.loc[idx, "email_sent_at"] = datetime.now(timezone.utc).isoformat()
                df.loc[idx, "email_error"] = None
                sent_count += 1
                print("sent")
            except Exception as e:  # noqa: BLE001 - log and continue, one bad address shouldn't kill the batch
                df.loc[idx, "email_sent"] = False
                df.loc[idx, "email_error"] = str(e)
                error_count += 1
                print(f"FAILED: {e}")

            if i % SAVE_EVERY == 0 or i == len(pending):
                save_progress(df)
                print(f"    saved progress -> {SCORED_CSV}")

            time.sleep(SLEEP_BETWEEN_EMAILS)
    finally:
        server.quit()

    print(f"\nDone. Sent: {sent_count}, Failed: {error_count}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--send", action="store_true", help="Actually send emails (default is dry run / preview only)")
    parser.add_argument("--yes", action="store_true", help="Skip the confirmation prompt before sending")
    parser.add_argument("--limit", type=int, default=None, help="Only process the first N pending rejections")
    args = parser.parse_args()

    load_dotenv()
    df = load_candidates()
    pending = get_pending_rejections(df, limit=args.limit)

    if pending.empty:
        print("Nothing to send — no rejected candidates with a pending email were found.")
        return

    if not args.send:
        # dry run never needs real SMTP credentials
        smtp_config = {
            "host": os.getenv("SMTP_HOST", "smtp.gmail.com"),
            "test_override_email": os.getenv("TEST_OVERRIDE_EMAIL"),
            "from_name": os.getenv("FROM_NAME", "Recruiting Team"),
            "from_email": os.getenv("FROM_EMAIL", "your_email@example.com"),
        }
        dry_run(df, pending, smtp_config)
        return

    smtp_config = load_smtp_config()
    send_all(df, pending, smtp_config, skip_confirm=args.yes)


if __name__ == "__main__":
    main()
